### ISSUE TITLE
Unable to create reverse relationship

### ISSUE THREAD

**Issue by saleem-git** [martsberger/django-joinfield#1]
First of all thank you for making the solution open source. I am using it in my project but am stuck with reverse relationship.
Here are my models

 class Collections(models.Model): 
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=200)
description = models.CharField(max_length=2000)
....

class Meta:
db_table = 'collections'

class CollectionViews(models.Model):
    id = models.BigAutoField(primary_key=True)
    collection_id = JoinField(Collections,on_delete=models.DO_NOTHING,db_column='collection_id',to_field='id')

page = models.CharField(max_length=100)
....

class Meta:
 db_table = 'collection_views'`

 Am able to do forward filters, but backward relationship fails this is my code for reverse relationship

`Collections.objects.filter(collection_views__page="listing")` 

also tried with actual model name 

`Collections.objects.filter(collectionviews_page='listing') ` 

I receive this error

`Cannot resolve keyword 'collectionviews' into field. Choices are: name, description......`

It tries to find the collectionviews in the field list but its a model.

**Comment by letitfly** [comment]
I am curious too but can you try this:
Collections.objects.filter(collectionviews__page='listing')

**Comment by saleem-git** [comment]
Am sorry for being to late? Please close the issue, the issue was with Django and not your module.
